storm.local.dir: "${SUPERVISOR_DATA_DIR}"
storm.log.dir: "${SUPERVISOR_LOGS_DIR}"
storm.log4j2.conf.dir: "${SUPERVISOR_LOGS_CONF_DIR}"

storm.zookeeper.servers:
  - "${ZK_SERVER_0}"
  - "${ZK_SERVER_1}"
storm.zookeeper.port: ${ZK_PORT}
storm.zookeeper.root: "${ZK_CHROOT}"

nimbus.seeds: ["${NIMBUS_FQDN}"]
nimbus.thrift.port: ${NIMBUS_THRIFT_PORT}

supervisor.slots.ports: ${SUPERVISOR_SLOT_PORTS}
supervisor.childopts: "${SUPERVISOR_CHILDOPTS}"
supervisor.memory.capacity.mb: ${SUPERVISOR_MEM_CAPACITY_MB}
supervisor.cpu.capacity: ${SUPERVISOR_CPU_CAPACITY}

worker.heap.memory.mb: ${WORKER_HEAP_MEMORY_MB}
worker.childopts: "${WORKER_CHILDOPTS}"
worker.gc.childopts: "${WORKER_GC_CHILDOPTS}"
