storm.local.hostname: "${NIMBUS_FQDN}"
storm.local.dir: "${NIMBUS_DATA_DIR}"
storm.log.dir: "${NIMBUS_LOGS_DIR}"
storm.log4j2.conf.dir: "${NIMBUS_LOGS_CONF_DIR}"

storm.zookeeper.servers: ${ZK_SERVERS}
storm.zookeeper.port: ${ZK_PORT}
storm.zookeeper.root: "${ZK_CHROOT}"

nimbus.thrift.port: ${NIMBUS_THRIFT_PORT}
nimbus.thrift.max_buffer_size: ${NIMBUS_THRIFT_MAX_BUFFER_SIZE}
nimbus.childopts: "${NIMBUS_CHILDOPTS}"
