version: "3.5"
services:
  pop-stormzk:
    container_name: pop-stormzk
    hostname: pop-stormzk
    networks:
      pop-series:
        ipv4_address: 175.0.0.10
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "2181:2181"
    volumes:
      - ./:/opt/pop-storm:ro
      - pop-stormzk-vol:/var/pop-storm
  pop-stormnimbus:
    container_name: pop-stormnimbus
    hostname: pop-stormnimbus
    networks:
      pop-series:
        ipv4_address: 175.0.0.11
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "6627:6627"
    volumes:
      - ./:/opt/pop-storm:ro
      - pop-stormnimbus-vol:/var/pop-storm
  pop-stormui:
    container_name: pop-stormui
    hostname: pop-stormui
    networks:
      pop-series:
        ipv4_address: 175.0.0.12
    restart: always
    deploy:
      resources:
        limits:
          memory: 384M
    ports:
      - "8080:8080"
    volumes:
      - ./:/opt/pop-storm:ro
      - pop-stormui-vol:/var/pop-storm
  pop-stormsupervisor:
    container_name: pop-stormsupervisor
    hostname: pop-stormsupervisor
    networks:
      pop-series:
        ipv4_address: 175.0.0.13
    deploy:
      resources:
        limits:
          memory: 4096M
    ports:
      - "6700:6700"     # worker port
      - "6701:6701"     # worker port
      - "16700:16700"   # jmx port (relative to worker port)
      - "16701:16701"   # jmx port
      - "46700:46700"   # additional port (relative to worker port, may use it to start a metric server, say prometheus)
      - "46701:46701"   # additional port
      - "56700:56700"   # debug port (relative to worker port)
      - "56701:56701"   # debug port
    volumes:
      - ./:/opt/pop-storm:ro
      - pop-stormsupervisor-vol:/var/pop-storm
volumes:
  pop-stormzk-vol:
    name: pop-stormzk-vol
  pop-stormnimbus-vol:
    name: pop-stormnimbus-vol
  pop-stormui-vol:
    name: pop-stormui-vol
  pop-stormsupervisor-vol:
    name: pop-stormsupervisor-vol
networks:
  pop-series:
    name: pop-series
    driver: bridge
    ipam:
      config:
        - subnet: 175.0.0.0/24
          gateway: 175.0.0.1
